name: HungerGames
version: '${project.version}'
main: me.cantankerousally.hungergames.HungerGames
api-version: '1.20'
commands:
  select:
    description: "Select an arena in HungerGames"
    usage: /<command>
  create:
    description: "Create an arena in HungerGames"
    usage: /<command>

