name: HungerGames
version: '${project.version}'
main: me.cantankerousally.hungergames.HungerGames
api-version: '1.20'
commands:
  select:
    description: "Select an arena in HungerGames"
    usage: /<command>
  create:
    description: "Create an arena in HungerGames"
    usage: /<command>
  chestrefill:
    description: "Refills Chests an arena in HungerGames"
    usage: /<command>
  supplydrop:
    description: "Drops a Supply Crate in HungerGames"
    usage: /<command>
  setspawn:
    description: "Sets SpawnPoints for Arenas in HungerGames"
    usage: /<command>
  start:
    description: "Starts the game in HungerGames"
    usage: /<command>
  end:
    description: "Forcefully Ends the game in HungerGames"
    usage: /<command>

