# Minimum and Maximum stacks of different items for regular chests
min-chest-content: 3
max-chest-content: 6
# Minimum and Maximum stacks of different items for bonus chests (Barrels by default)
min-barrel-content: 4
max-barrel-content: 7
# Minimum and Maximum stacks of different items for center chests (Trapped Chests by default)
min-trapped-chest-content: 4
max-trapped-chest-content: 7
# Number of supply-drops dropped simultaneously, 1 by default
num-supply-drops: 1
# Minimum and Maximum stacks of different items for supply drops (Shulker Boxes by default)
min-supply-drop-content: 2
max-supply-drop-content: 6
# Minimum and Maximum stacks of different items for supply drops (Shulker Boxes by default)
game-time: 900
grace-period: 30
supplydrop:
  interval: 30
chestrefill:
  time: 600
border:
  size: 100.0
  start-time: 180
  end-time: 780
  final-size: 40
  center-x: 0
  center-z: 0
bedrock-buff:
  enabled: false
  effects:
    - DAMAGE_RESISTANCE
    - SPEED
killer-effects:
  - effect: DAMAGE_RESISTANCE
    duration: 300
    level: 0
  - effect: INCREASE_DAMAGE
    duration: 300
    level: 0
  - effect: REGENERATION
    duration: 600
    level: 0